# Generated by Django 5.0.7 on 2024-07-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_cardcomment_related_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='categories',
            field=models.JSONField(choices=[('cat1', [('subcat1', 'smth')]), ('cat2', [('subcat2', 'smth'), ('subcat3', 'smth')])], default='subcat2'),
            preserve_default=False,
        ),
    ]
