# Generated by Django 5.0.7 on 2024-07-22 18:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_alter_card_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('cat1', [('subcat1', 'smth')]), ('cat2', [('subcat2', 'smth'), ('subcat3', 'smth')])], max_length=255), size=None),
        ),
    ]
