# Generated by Django 5.0.7 on 2024-07-24 09:26

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_alter_card_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cat1', [('subcat1', 'smth')]), ('cat2', [('subcat2', 'smth'), ('subcat3', 'smth')])], max_length=9, null=True),
        ),
    ]
