# Generated by Django 5.0.7 on 2024-07-24 09:39

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0017_alter_card_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cat1', [('subcat1', 'smth1')]), ('cat2', [('subcat2', 'smth2'), ('subcat3', 'smth3')])], default={}, max_length=9),
            preserve_default=False,
        ),
    ]
